### ISSUE TITLE
Piano Key Labels

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/learn-music#47]
My biggest challenge in learning the piano is which keys correspond to the notes in the music. I can deduce them slowly, but it’s painful.
What I would like to have is the notes on the keys so that I can immediately see what “line” they correspond to on the sheet music.

Piano Keyboard Stickers for 88/61/ 54/49 Key,Colorful Transparent Removable for kids Beginners (Full Color)
https://www.amazon.com/gp/aw/d/B088NJHT92

![473A0DE4-A2B1-4ECF-A504-26B37D66234D](https://user-images.githubusercontent.com/194400/136800340-77b27127-bd71-4eed-a76b-5777af594551.jpeg)

@iteles any objections to us sticking these on the piano keys (they are non-destructive and can easily be removed if we don’t like them…) ?

Related to #46 (theory poster)

**Comment by iteles** [comment]
This is apparently a very hot topic in the world of piano teachers 🤷‍♀️ 

The obvious downside is that this adds an extra step in that people have to then be weaned off the labels (much as you would learn touch typing on a computer keyboard) but I would suspect it also leads to fewer people quitting up front.
Of course you can't actually play a piece of music looking at the keys (unless you've memorised it) so this is a natural progression anyway.

There is no scientific evidence one way or the other as far as I can find, but I _have_ found quite a few people advocating for _colour coding_ the keys rather than using the letters of the keys themselves:

https://takelessons.com/blog/labeled-piano-keys
![image](https://user-images.githubusercontent.com/4185328/136827236-81db676d-302b-4dac-8891-c6cd3faf846c.png)


These guys actually _sell_ labels so their opinion is a little suspect but they suggest that up until the age of 8, they are useful, but **not after the age of 8**.
https://crosbyaudio.com/blogs/news/do-piano-stickers-help-or-hinder-learning
![image](https://user-images.githubusercontent.com/4185328/136827821-b41312f2-4c85-4277-be5b-dc79d405056b.png)

They also suggest that ***having fun is crucial to learning*** (which we know to be true) and for me is not only a vote for labels but also a vote for considering fun labels with animals or colours rather than just the letters.

What do you think?

**Comment by nelsonic** [comment]
@iteles I _agree_ with colors as it adds an additional reference point for communication. 
But I honestly don't see the advantage to the "animals"; not even for children. 
The _intrinsic_ motivation of making beautiful sounds/music is _way_ more interesting than any monster letters. 

As a _non_ piano player who can sit and _deduce_ the notes by working from middle C, I feel that there's a completely _unnecessary_ barrier to entry in learning to play the piano which will immediately be overcome by having these stickers.
If I'd had them when I was younger I would not have suffered as much. 

The analogy of a computer keyboard with the letters on the keys being more beginner-friendly than blank keys is what I was arguing with the "Piano Teachers" ... I don't feel that having the letters on the keys hindered my learning how to touch-type. I think it would have been **_deeply_ frustrating** to not have them when I was first trying a computer keyboard. I could probably remove the key letters on my Mac Keyboard now and be 99% fine. 

Any objection to me getting these that have the "ABC", "DO RE MI" and the notes?
https://www.amazon.es/-/pt/dp/B07QZQLQTF
![image](https://user-images.githubusercontent.com/194400/136862483-af9c82c4-c3a2-447b-a51e-cd6aa8cba371.png)

![image](https://user-images.githubusercontent.com/194400/136862526-5c104789-0713-4c63-9d49-0a8467c855cf.png)

**Comment by nelsonic** [comment]
Added to the Amazon.es shopping cart. Could already checkout as have enough for free postage. Do you need anything? 💭

**Comment by nelsonic** [comment]
Amazon order including piano key labels placed today. Should arrive early next week. (No next-day-delivery here … 🙄) ⏳

**Comment by iteles** [comment]
@nelsonic These have arrived and have been put on the piano 🎉 

Any further actions required?

**Comment by nelsonic** [comment]
@iteles no further actions. 
Ana put them on well:

![image](https://user-images.githubusercontent.com/194400/140103997-e8cc15f5-d9cd-4d1a-bc8b-e470508bf57e.png)

Closing. ✅  (thanks for the reminder)
